version: "3.8"

services:
  notification_container:
    container_name: notification_container
    build: ./
    command: ./wait-for-db.sh ./notification_service
    environment:
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_CONSUMER=${KAFKA_CONSUMER}


      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
    networks:
      - shopongo_default
    ports:
      - "8079:8079"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - shopongo_default
    ports:
      - "27017:27017"

networks:
  shopongo_default:
    external: true

volumes:
  mongo_data:
